---
kind: Service
apiVersion: v1
metadata:
  name: csi-cosplugin-external-runner
  namespace: kube-system
  labels:
    app: csi-cosplugin-external-runner
spec:
  selector:
    app: csi-cosplugin-external-runner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-cosplugin-external-runner
  namespace: kube-system
spec:
  serviceName: "csi-cosplugin-external-runner"
  replicas: 1
  selector:
    matchLabels:
      app: csi-cosplugin-external-runner
  template:
    metadata:
      labels:
        app: csi-cosplugin-external-runner
    spec:
      serviceAccount: csi-cos-tencentcloud
      priorityClassName: system-node-critical
      containers:
        - name: csi-attacher
          image: ccr.ccs.tencentyun.com/tkeimages/csi-attacher:0.3.0
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: cosfs
          image: ccr.ccs.tencentyun.com/tkeimages/csi-tencentcloud-cos:0.3.0
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy
      volumes:
        - name: socket-dir
          emptyDir: {}
